### ISSUE TITLE
Error with 527 organization

### ISSUE THREAD

**Issue by jdd10** [palewire/moneyinpolitics.wtf#149]
### The word

527 organization

### Error report

word should be "predominantly" not "predominately" (which isn't a word and if it was would mean something different)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by palewire** [comment]
Thanks for the bug report. According to the Merriam-Webster online dictionary, the two words are synonyms.

![Screenshot 2024-07-16 6 12 46 PM](https://github.com/user-attachments/assets/792e403a-edcc-43e3-b9f9-6e570dff26e6)
![Screenshot 2024-07-16 6 17 32 PM](https://github.com/user-attachments/assets/1bd8ea4a-b1b7-4cc3-9eb9-579d077742b1)

While I see the words used interchangeably in AP news stories, which I consider a style setter, I suspect predominantly is more commonly used than predominately. I'll make this edit.

**Comment by palewire** [comment]
This issue was fixed with https://github.com/palewire/moneyinpolitics.wtf/commit/2133fe7c920a92cd026290b3e9e8798e9a07b98b
