### ISSUE TITLE
Request a word for reporting thresholds

### ISSUE THREAD

**Issue by jdd10** [palewire/moneyinpolitics.wtf#155]
### The word

reporting threshold

### Where have you encountered it?

discussions of small donors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by palewire** [comment]
Thanks for this submission. Here are two examples I found in Google News. Do they reflect what you have in mind?

[Montana Free Press](https://montanafreepress.org/2024/04/19/tester-first-quarter-fundraising-more-than-double-sheehys/):
> John Driscoll, a former speaker of the state House in the 1970s, has not filed campaign finance data with the Federal Election Commission, suggesting he has not raised or spent more than $5,000, the reporting threshold. 

[Providence Journal](https://www.providencejournal.com/story/news/politics/state/2023/06/05/rhode-island-political-donation-laws-individual-contribution-limit-could-change/70289436007/)
> Although some parts of the bill address longstanding concerns, the increase in individual donation limits and reporting threshold is drawing alarm from progressive Democrats and good-government groups.

**Comment by jdd10** [comment]
Yes, exactly.

From: Ben Welsh ***@***.***>
Date: Thursday, August 29, 2024 at 3:35 PM
To: palewire/moneyinpolitics.wtf ***@***.***>
Cc: Jeremy D. Darrington ***@***.***>, Author ***@***.***>
Subject: Re: [palewire/moneyinpolitics.wtf] Request a word for reporting thresholds (Issue #155)

Thanks for this submission. Here are two examples I found in Google News. Do they reflect what you have in mind?

Montana Free Press<https://montanafreepress.org/2024/04/19/tester-first-quarter-fundraising-more-than-double-sheehys/>:

John Driscoll, a former speaker of the state House in the 1970s, has not filed campaign finance data with the Federal Election Commission, suggesting he has not raised or spent more than $5,000, the reporting threshold.

Providence Journal<https://www.providencejournal.com/story/news/politics/state/2023/06/05/rhode-island-political-donation-laws-individual-contribution-limit-could-change/70289436007/>

Although some parts of the bill address longstanding concerns, the increase in individual donation limits and reporting threshold is drawing alarm from progressive Democrats and good-government groups.
