### ISSUE TITLE
Flag an error--expand button links to wrong entries from search

### ISSUE THREAD

**Issue by jdd10** [palewire/moneyinpolitics.wtf#156]
### The word

in

### Error report

when typing anything in the search box, like "in", the Expand button links to the wrong definition entry on any of the returned entries. Notice the bottom entry is being hovered and look at the URL:
<img width="652" alt="image" src="https://github.com/user-attachments/assets/8ee92a59-9fb6-4b18-aed6-ebd91f2d4b70">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by palewire** [comment]
I believe I've fixed this issue. Thank you for reporting it.
