### ISSUE TITLE
Word request: Political Advocacy Organization

### ISSUE THREAD

**Issue by palewire** [palewire/moneyinpolitics.wtf#193]
### The word

Political Advocacy Organization

### Where have you encountered it?

https://www.seacoastonline.com/story/news/2024/11/04/new-campaign-finance-law-allows-record-spending-in-nh-governor-race/75986527007/

https://jcrc.org/blog/bay-area-jewish-action-formed/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dwillis** [comment]
Isn't this just a 501c4?

**Comment by palewire** [comment]
Yes, I think so. I'm just seeing it used a standalone word in stories like the the one below and I wonder if we should define it.

https://www.seacoastonline.com/story/news/2024/11/04/new-campaign-finance-law-allows-record-spending-in-nh-governor-race/75986527007/

**Comment by dwillis** [comment]
I think we add it to the 501c4 or just have it point to it?
