### ISSUE TITLE
Spelling fix in PAC definition

### ISSUE THREAD

**Issue by anthonydb** [palewire/moneyinpolitics.wtf#69]
### The word

PAC

### Error report

Change spelling: `separately` instead of `seperately`.

Thanks for this site -- very helpful as I am taking on campaign finance duties!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by palewire** [comment]
Thanks. I think I just shipped that fix out. Should show up in a minute or two.

**Comment by anthonydb** [comment]
My little contribution ... 
Thanks!
