### ISSUE TITLE
Request a word

### ISSUE THREAD

**Issue by shirshod** [palewire/moneyinpolitics.wtf#72]
### The word

Leadership PAC

### Where have you encountered it?

Political stories surrounding fundraising.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by palewire** [comment]
There's a first pass at this in #71. Let us know what you think.

**Comment by palewire** [comment]
This one has merged. Thanks for the request! Let us know what you think of the result. And if you have any other additions or edits you'd like to see please speak up!
